services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=guild_manager_user
      - POSTGRES_PASSWORD=guild_manager_password
      - POSTGRES_DB=guild_manager_db
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - '8085:8080'
    depends_on:
      - db

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm --prefix backend run dev
    ports:
      - '3000:3000'
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_URL=postgresql://guild_manager_user:guild_manager_password@db:5432/guild_manager_db
    depends_on:
      - db
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules

  frontend:
    build:
      context: ./frontend
      target: build
    command: npm start
    ports:
      - '4200:4200'
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:
