// Generated by scripts/landing-screenshots.mjs, do not edit.
export const SHOT_SIZES = {
  fr: {
    overview: { width: 2320, height: 1376 },
    ranking: { width: 2320, height: 860 },
    awards: { width: 2320, height: 818 },
    progression: { width: 2320, height: 1108 },
    deaths: { width: 2320, height: 1734 },
    lineup: { width: 2320, height: 1910 },
    mplus: { width: 2320, height: 2304 },
    calendar: { width: 2320, height: 1738 },
  },
  en: {
    overview: { width: 2320, height: 1376 },
    ranking: { width: 2320, height: 860 },
    awards: { width: 2320, height: 788 },
    progression: { width: 2320, height: 1108 },
    deaths: { width: 2320, height: 1734 },
    lineup: { width: 2320, height: 1754 },
    mplus: { width: 2320, height: 2254 },
    calendar: { width: 2320, height: 1738 },
  },
} as const;
